name: Spotify Now Playing

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spotify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          filename: images/spotify.svg

          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_music: yes
          plugin_music_provider: spotify

          plugin_music_token: ${{ secrets.SPOTIFY_CLIENT_ID }}
          plugin_music_user: current
          plugin_music_mode: recent

        env:
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Spotify"
