name: Spotify Now Playing

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Spotify Now Playing
        uses: kittinan/spotify-github-profile@master
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          commit_message: "Update Spotify Now Playing"
